# Generated by Django 6.0.3 on 2026-03-06 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermerchantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermerchantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
